#!/usr/bin/env node

var mongoose = require('mongoose')
  , cli = require('./cli')
  , config = require('mapcache-config');

var operations = cli.operations;

var yargs = require("yargs")
  .usage("Usage: $0 <command> [options]")
  .alias('d', 'debug')
  .help('help')
  .check(function(argv, opts){
    if(!operations[argv._[0]]) {
      console.log('Invalid command <'+argv._[0]+'>');
      console.log('Valid commands are:');
      for (var key in operations) {
        if (operations.hasOwnProperty(key)) {
          console.log('\t'+key);
        }
      }
      process.exit();
    }
  });

for(var key in operations) {
  if (operations.hasOwnProperty(key)) {
    yargs.command(key, key, operations[key]);
  }
}

var argv = yargs.argv;

var mongodbConfig = config.server.mongodb;

var mongoUri = "mongodb://" + mongodbConfig.host + "/" + mongodbConfig.db;
mongoose.connect(mongoUri, {server: {poolSize: mongodbConfig.poolSize}}, function(err) {
  if (err) {
    console.log('Error connecting to mongo database, please make sure mongodb is running...');
    throw err;
  }
});

mongoose.set('debug', argv.d);
